name: CI

on: [push]

jobs:
  test:
    name: Test_macOS
    runs-on: macos-latest
    strategy:
        matrix:
          destination: [macOS-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Test_macOS
        run: |
          xcodebuild clean build test -project EssentialFeed/EssentialFeed.xcodeproj -scheme "CI_macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES
        env: 
         destination: ${{ matrix.destination }}
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_14.3.app
      - name: Test_iOS
        run: |
          xcodebuild clean build test -workspace EssentialApp/EssentialApp.xcworkspace -scheme "CI_iOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,OS=16.4,name=iPhone 14 Pro" ONLY_ACTIVE_ARCH=YES 
        env: 
         destination: ${{ matrix.destination }}
