name: CI

on: [push]

jobs:
  test:
    name: Test_macOS
    runs-on: macos-latest
    strategy:
        matrix:
          destination: [macOS-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Test_macOS
        run: |
          xcodebuild clean build test -project EssentialFeed/EssentialFeed.xcodeproj -scheme "CI_macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES
        env: 
         destination: ${{ matrix.destination }}
  build-and-test:
    # The type of runner that the job will run on
    runs-on: macos-13

    timeout-minutes: 10

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@master

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_14.3.app

    - name: Xcode version
      run: /usr/bin/xcodebuild -version

    - name: Build and Test
      run: xcodebuild clean build test -workspace EssentialApp/EssentialApp.xcworkspace -scheme "CI_iOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 14 Pro,OS=16.4" ONLY_ACTIVE_ARCH=YES
