name: CI-Test

on: [push]

jobs:
  test:
    name: Test
    runs-on: macos-latest
    strategy:
        matrix:
          destination: [macOS-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Test
        run: |
          xcodebuild clean build test -project EssentialFeed/EssentialFeed.xcodeproj -scheme "CI" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
        env: 
         destination: ${{ matrix.destination }}
